### ISSUE TITLE
Random Number Generator

### ISSUE THREAD

**Issue by Honzecki** [CollierPlays/Micrabot#5]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

_**without comment**_

**Describe the solution you'd like**

_I would like if there was a Random Number generator in the bot. **example** !number {from} {to}
And it would generate a random number between those two numbers the user has included_

**Describe alternatives you've considered**

**Additional context**

_I really think that is all I need to say._

**Comment by CollierPlays** [comment]
Ok, i have added it to our todo list!

**Comment by CollierPlays** [comment]
It is now in progress!

**Comment by CollierPlays** [comment]
Added!
